framework:
    http_client:
        scoped_clients:
            lemon_squeezy.client:
                base_uri: 'https://api.lemonsqueezy.com/v1/'
                auth_bearer: '%env(LEMON_SQUEEZY_API_KEY)%'
                headers:
                    Accept: 'application/vnd.api+json'
                    Content-Type: 'application/vnd.api+json'